### ISSUE TITLE
Openstack vm/instance without image associated - TypeError: string indices must be integers

### ISSUE THREAD

**Issue by eduardocerqueira** [eduardocerqueira/janitor#3]
when an instance/vm doesn't have the image associated Janitor is throwing this error and exit(1). It needs to be treated and set properly in case the instance/vm does not have the image ( that it can happens )

```
13:16:46 + python janitor/cli.py openstack --openrc /var/lib/jenkins/secure_creds/openrc.sh --whitelist ../insights-tests/jenkins/jobs/janitor_whitelist.txt
13:16:50 Traceback (most recent call last):
13:16:50   File "janitor/cli.py", line 59, in <module>
13:16:50     janitor()
13:16:50   File "janitor/cli.py", line 55, in janitor
13:16:50     cli(prog_name='janitor')
13:16:50   File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
13:16:50     return self.main(*args, **kwargs)
13:16:50   File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
13:16:50     rv = self.invoke(ctx)
13:16:50   File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
13:16:50     return _process_result(sub_ctx.command.invoke(sub_ctx))
13:16:50   File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
13:16:50     return ctx.invoke(self.callback, **ctx.params)
13:16:50   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
13:16:50     return callback(*args, **kwargs)
13:16:50   File "janitor/cli.py", line 39, in openstack
13:16:50     vms = openstack.get_all_instances()
13:16:50   File "/var/lib/jenkins/jobs/janitor/workspace/janitor/janitor/provider/openstack.py", line 91, in get_all_instances
13:16:50     image = self.glance.images.get(vm.image['id'])
13:16:50 TypeError: string indices must be integers
```

**Comment by eduardocerqueira** [comment]
Fixed and new build https://copr.fedorainfracloud.org/coprs/eduardocerqueira/janitor/build/707752/ completed.

RPM packages available: https://copr.fedorainfracloud.org/coprs/eduardocerqueira/janitor/packages/
